export * from './classes.sql';
export * from './experiments-tools.sql';
export * from './experiments.sql';
export * from './groups.sql';
export * from './schedules-tools.sql';
export * from './schedules.sql';
export * from './students.sql';
export * from './tools.sql';
export * from './users.sql';
