/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AppAboutImport } from './routes/_app/about'
import { Route as AppToolsIndexImport } from './routes/_app/tools/index'
import { Route as AppStudentsIndexImport } from './routes/_app/students/index'
import { Route as AppSchedulesIndexImport } from './routes/_app/schedules/index'
import { Route as AppGroupsIndexImport } from './routes/_app/groups/index'
import { Route as AppExperimentsIndexImport } from './routes/_app/experiments/index'
import { Route as AppClassesIndexImport } from './routes/_app/classes/index'
import { Route as AppToolsCreateImport } from './routes/_app/tools/create'
import { Route as AppStudentsCreateImport } from './routes/_app/students/create'
import { Route as AppSettingsDataManagementImport } from './routes/_app/settings/data-management'
import { Route as AppSchedulesCreateImport } from './routes/_app/schedules/create'
import { Route as AppGroupsCreateImport } from './routes/_app/groups/create'
import { Route as AppExperimentsCreateImport } from './routes/_app/experiments/create'
import { Route as AppClassesCreateImport } from './routes/_app/classes/create'
import { Route as AppToolsIdIndexImport } from './routes/_app/tools/$id/index'
import { Route as AppStudentsIdIndexImport } from './routes/_app/students/$id/index'
import { Route as AppSchedulesIdIndexImport } from './routes/_app/schedules/$id/index'
import { Route as AppGroupsIdIndexImport } from './routes/_app/groups/$id/index'
import { Route as AppExperimentsIdIndexImport } from './routes/_app/experiments/$id/index'
import { Route as AppClassesIdIndexImport } from './routes/_app/classes/$id/index'
import { Route as AppToolsIdEditImport } from './routes/_app/tools/$id/edit'
import { Route as AppStudentsIdEditImport } from './routes/_app/students/$id/edit'
import { Route as AppSchedulesIdEditImport } from './routes/_app/schedules/$id/edit'
import { Route as AppGroupsIdEditImport } from './routes/_app/groups/$id/edit'
import { Route as AppExperimentsIdEditImport } from './routes/_app/experiments/$id/edit'
import { Route as AppClassesIdEditImport } from './routes/_app/classes/$id/edit'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AppAboutRoute = AppAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)

const AppToolsIndexRoute = AppToolsIndexImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AppRoute,
} as any)

const AppStudentsIndexRoute = AppStudentsIndexImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)

const AppSchedulesIndexRoute = AppSchedulesIndexImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => AppRoute,
} as any)

const AppGroupsIndexRoute = AppGroupsIndexImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)

const AppExperimentsIndexRoute = AppExperimentsIndexImport.update({
  id: '/experiments/',
  path: '/experiments/',
  getParentRoute: () => AppRoute,
} as any)

const AppClassesIndexRoute = AppClassesIndexImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => AppRoute,
} as any)

const AppToolsCreateRoute = AppToolsCreateImport.update({
  id: '/tools/create',
  path: '/tools/create',
  getParentRoute: () => AppRoute,
} as any)

const AppStudentsCreateRoute = AppStudentsCreateImport.update({
  id: '/students/create',
  path: '/students/create',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsDataManagementRoute = AppSettingsDataManagementImport.update({
  id: '/settings/data-management',
  path: '/settings/data-management',
  getParentRoute: () => AppRoute,
} as any)

const AppSchedulesCreateRoute = AppSchedulesCreateImport.update({
  id: '/schedules/create',
  path: '/schedules/create',
  getParentRoute: () => AppRoute,
} as any)

const AppGroupsCreateRoute = AppGroupsCreateImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => AppRoute,
} as any)

const AppExperimentsCreateRoute = AppExperimentsCreateImport.update({
  id: '/experiments/create',
  path: '/experiments/create',
  getParentRoute: () => AppRoute,
} as any)

const AppClassesCreateRoute = AppClassesCreateImport.update({
  id: '/classes/create',
  path: '/classes/create',
  getParentRoute: () => AppRoute,
} as any)

const AppToolsIdIndexRoute = AppToolsIdIndexImport.update({
  id: '/tools/$id/',
  path: '/tools/$id/',
  getParentRoute: () => AppRoute,
} as any)

const AppStudentsIdIndexRoute = AppStudentsIdIndexImport.update({
  id: '/students/$id/',
  path: '/students/$id/',
  getParentRoute: () => AppRoute,
} as any)

const AppSchedulesIdIndexRoute = AppSchedulesIdIndexImport.update({
  id: '/schedules/$id/',
  path: '/schedules/$id/',
  getParentRoute: () => AppRoute,
} as any)

const AppGroupsIdIndexRoute = AppGroupsIdIndexImport.update({
  id: '/groups/$id/',
  path: '/groups/$id/',
  getParentRoute: () => AppRoute,
} as any)

const AppExperimentsIdIndexRoute = AppExperimentsIdIndexImport.update({
  id: '/experiments/$id/',
  path: '/experiments/$id/',
  getParentRoute: () => AppRoute,
} as any)

const AppClassesIdIndexRoute = AppClassesIdIndexImport.update({
  id: '/classes/$id/',
  path: '/classes/$id/',
  getParentRoute: () => AppRoute,
} as any)

const AppToolsIdEditRoute = AppToolsIdEditImport.update({
  id: '/tools/$id/edit',
  path: '/tools/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

const AppStudentsIdEditRoute = AppStudentsIdEditImport.update({
  id: '/students/$id/edit',
  path: '/students/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

const AppSchedulesIdEditRoute = AppSchedulesIdEditImport.update({
  id: '/schedules/$id/edit',
  path: '/schedules/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

const AppGroupsIdEditRoute = AppGroupsIdEditImport.update({
  id: '/groups/$id/edit',
  path: '/groups/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

const AppExperimentsIdEditRoute = AppExperimentsIdEditImport.update({
  id: '/experiments/$id/edit',
  path: '/experiments/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

const AppClassesIdEditRoute = AppClassesIdEditImport.update({
  id: '/classes/$id/edit',
  path: '/classes/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutImport
      parentRoute: typeof AppImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/classes/create': {
      id: '/_app/classes/create'
      path: '/classes/create'
      fullPath: '/classes/create'
      preLoaderRoute: typeof AppClassesCreateImport
      parentRoute: typeof AppImport
    }
    '/_app/experiments/create': {
      id: '/_app/experiments/create'
      path: '/experiments/create'
      fullPath: '/experiments/create'
      preLoaderRoute: typeof AppExperimentsCreateImport
      parentRoute: typeof AppImport
    }
    '/_app/groups/create': {
      id: '/_app/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AppGroupsCreateImport
      parentRoute: typeof AppImport
    }
    '/_app/schedules/create': {
      id: '/_app/schedules/create'
      path: '/schedules/create'
      fullPath: '/schedules/create'
      preLoaderRoute: typeof AppSchedulesCreateImport
      parentRoute: typeof AppImport
    }
    '/_app/settings/data-management': {
      id: '/_app/settings/data-management'
      path: '/settings/data-management'
      fullPath: '/settings/data-management'
      preLoaderRoute: typeof AppSettingsDataManagementImport
      parentRoute: typeof AppImport
    }
    '/_app/students/create': {
      id: '/_app/students/create'
      path: '/students/create'
      fullPath: '/students/create'
      preLoaderRoute: typeof AppStudentsCreateImport
      parentRoute: typeof AppImport
    }
    '/_app/tools/create': {
      id: '/_app/tools/create'
      path: '/tools/create'
      fullPath: '/tools/create'
      preLoaderRoute: typeof AppToolsCreateImport
      parentRoute: typeof AppImport
    }
    '/_app/classes/': {
      id: '/_app/classes/'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/experiments/': {
      id: '/_app/experiments/'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof AppExperimentsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/schedules/': {
      id: '/_app/schedules/'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AppSchedulesIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/tools/': {
      id: '/_app/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/classes/$id/edit': {
      id: '/_app/classes/$id/edit'
      path: '/classes/$id/edit'
      fullPath: '/classes/$id/edit'
      preLoaderRoute: typeof AppClassesIdEditImport
      parentRoute: typeof AppImport
    }
    '/_app/experiments/$id/edit': {
      id: '/_app/experiments/$id/edit'
      path: '/experiments/$id/edit'
      fullPath: '/experiments/$id/edit'
      preLoaderRoute: typeof AppExperimentsIdEditImport
      parentRoute: typeof AppImport
    }
    '/_app/groups/$id/edit': {
      id: '/_app/groups/$id/edit'
      path: '/groups/$id/edit'
      fullPath: '/groups/$id/edit'
      preLoaderRoute: typeof AppGroupsIdEditImport
      parentRoute: typeof AppImport
    }
    '/_app/schedules/$id/edit': {
      id: '/_app/schedules/$id/edit'
      path: '/schedules/$id/edit'
      fullPath: '/schedules/$id/edit'
      preLoaderRoute: typeof AppSchedulesIdEditImport
      parentRoute: typeof AppImport
    }
    '/_app/students/$id/edit': {
      id: '/_app/students/$id/edit'
      path: '/students/$id/edit'
      fullPath: '/students/$id/edit'
      preLoaderRoute: typeof AppStudentsIdEditImport
      parentRoute: typeof AppImport
    }
    '/_app/tools/$id/edit': {
      id: '/_app/tools/$id/edit'
      path: '/tools/$id/edit'
      fullPath: '/tools/$id/edit'
      preLoaderRoute: typeof AppToolsIdEditImport
      parentRoute: typeof AppImport
    }
    '/_app/classes/$id/': {
      id: '/_app/classes/$id/'
      path: '/classes/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof AppClassesIdIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/experiments/$id/': {
      id: '/_app/experiments/$id/'
      path: '/experiments/$id'
      fullPath: '/experiments/$id'
      preLoaderRoute: typeof AppExperimentsIdIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/groups/$id/': {
      id: '/_app/groups/$id/'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AppGroupsIdIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/schedules/$id/': {
      id: '/_app/schedules/$id/'
      path: '/schedules/$id'
      fullPath: '/schedules/$id'
      preLoaderRoute: typeof AppSchedulesIdIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/students/$id/': {
      id: '/_app/students/$id/'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AppStudentsIdIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/tools/$id/': {
      id: '/_app/tools/$id/'
      path: '/tools/$id'
      fullPath: '/tools/$id'
      preLoaderRoute: typeof AppToolsIdIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClassesCreateRoute: typeof AppClassesCreateRoute
  AppExperimentsCreateRoute: typeof AppExperimentsCreateRoute
  AppGroupsCreateRoute: typeof AppGroupsCreateRoute
  AppSchedulesCreateRoute: typeof AppSchedulesCreateRoute
  AppSettingsDataManagementRoute: typeof AppSettingsDataManagementRoute
  AppStudentsCreateRoute: typeof AppStudentsCreateRoute
  AppToolsCreateRoute: typeof AppToolsCreateRoute
  AppClassesIndexRoute: typeof AppClassesIndexRoute
  AppExperimentsIndexRoute: typeof AppExperimentsIndexRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppSchedulesIndexRoute: typeof AppSchedulesIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
  AppClassesIdEditRoute: typeof AppClassesIdEditRoute
  AppExperimentsIdEditRoute: typeof AppExperimentsIdEditRoute
  AppGroupsIdEditRoute: typeof AppGroupsIdEditRoute
  AppSchedulesIdEditRoute: typeof AppSchedulesIdEditRoute
  AppStudentsIdEditRoute: typeof AppStudentsIdEditRoute
  AppToolsIdEditRoute: typeof AppToolsIdEditRoute
  AppClassesIdIndexRoute: typeof AppClassesIdIndexRoute
  AppExperimentsIdIndexRoute: typeof AppExperimentsIdIndexRoute
  AppGroupsIdIndexRoute: typeof AppGroupsIdIndexRoute
  AppSchedulesIdIndexRoute: typeof AppSchedulesIdIndexRoute
  AppStudentsIdIndexRoute: typeof AppStudentsIdIndexRoute
  AppToolsIdIndexRoute: typeof AppToolsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppIndexRoute: AppIndexRoute,
  AppClassesCreateRoute: AppClassesCreateRoute,
  AppExperimentsCreateRoute: AppExperimentsCreateRoute,
  AppGroupsCreateRoute: AppGroupsCreateRoute,
  AppSchedulesCreateRoute: AppSchedulesCreateRoute,
  AppSettingsDataManagementRoute: AppSettingsDataManagementRoute,
  AppStudentsCreateRoute: AppStudentsCreateRoute,
  AppToolsCreateRoute: AppToolsCreateRoute,
  AppClassesIndexRoute: AppClassesIndexRoute,
  AppExperimentsIndexRoute: AppExperimentsIndexRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppSchedulesIndexRoute: AppSchedulesIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
  AppClassesIdEditRoute: AppClassesIdEditRoute,
  AppExperimentsIdEditRoute: AppExperimentsIdEditRoute,
  AppGroupsIdEditRoute: AppGroupsIdEditRoute,
  AppSchedulesIdEditRoute: AppSchedulesIdEditRoute,
  AppStudentsIdEditRoute: AppStudentsIdEditRoute,
  AppToolsIdEditRoute: AppToolsIdEditRoute,
  AppClassesIdIndexRoute: AppClassesIdIndexRoute,
  AppExperimentsIdIndexRoute: AppExperimentsIdIndexRoute,
  AppGroupsIdIndexRoute: AppGroupsIdIndexRoute,
  AppSchedulesIdIndexRoute: AppSchedulesIdIndexRoute,
  AppStudentsIdIndexRoute: AppStudentsIdIndexRoute,
  AppToolsIdIndexRoute: AppToolsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/about': typeof AppAboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/classes/create': typeof AppClassesCreateRoute
  '/experiments/create': typeof AppExperimentsCreateRoute
  '/groups/create': typeof AppGroupsCreateRoute
  '/schedules/create': typeof AppSchedulesCreateRoute
  '/settings/data-management': typeof AppSettingsDataManagementRoute
  '/students/create': typeof AppStudentsCreateRoute
  '/tools/create': typeof AppToolsCreateRoute
  '/classes': typeof AppClassesIndexRoute
  '/experiments': typeof AppExperimentsIndexRoute
  '/groups': typeof AppGroupsIndexRoute
  '/schedules': typeof AppSchedulesIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/tools': typeof AppToolsIndexRoute
  '/classes/$id/edit': typeof AppClassesIdEditRoute
  '/experiments/$id/edit': typeof AppExperimentsIdEditRoute
  '/groups/$id/edit': typeof AppGroupsIdEditRoute
  '/schedules/$id/edit': typeof AppSchedulesIdEditRoute
  '/students/$id/edit': typeof AppStudentsIdEditRoute
  '/tools/$id/edit': typeof AppToolsIdEditRoute
  '/classes/$id': typeof AppClassesIdIndexRoute
  '/experiments/$id': typeof AppExperimentsIdIndexRoute
  '/groups/$id': typeof AppGroupsIdIndexRoute
  '/schedules/$id': typeof AppSchedulesIdIndexRoute
  '/students/$id': typeof AppStudentsIdIndexRoute
  '/tools/$id': typeof AppToolsIdIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof AppAboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/classes/create': typeof AppClassesCreateRoute
  '/experiments/create': typeof AppExperimentsCreateRoute
  '/groups/create': typeof AppGroupsCreateRoute
  '/schedules/create': typeof AppSchedulesCreateRoute
  '/settings/data-management': typeof AppSettingsDataManagementRoute
  '/students/create': typeof AppStudentsCreateRoute
  '/tools/create': typeof AppToolsCreateRoute
  '/classes': typeof AppClassesIndexRoute
  '/experiments': typeof AppExperimentsIndexRoute
  '/groups': typeof AppGroupsIndexRoute
  '/schedules': typeof AppSchedulesIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/tools': typeof AppToolsIndexRoute
  '/classes/$id/edit': typeof AppClassesIdEditRoute
  '/experiments/$id/edit': typeof AppExperimentsIdEditRoute
  '/groups/$id/edit': typeof AppGroupsIdEditRoute
  '/schedules/$id/edit': typeof AppSchedulesIdEditRoute
  '/students/$id/edit': typeof AppStudentsIdEditRoute
  '/tools/$id/edit': typeof AppToolsIdEditRoute
  '/classes/$id': typeof AppClassesIdIndexRoute
  '/experiments/$id': typeof AppExperimentsIdIndexRoute
  '/groups/$id': typeof AppGroupsIdIndexRoute
  '/schedules/$id': typeof AppSchedulesIdIndexRoute
  '/students/$id': typeof AppStudentsIdIndexRoute
  '/tools/$id': typeof AppToolsIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/classes/create': typeof AppClassesCreateRoute
  '/_app/experiments/create': typeof AppExperimentsCreateRoute
  '/_app/groups/create': typeof AppGroupsCreateRoute
  '/_app/schedules/create': typeof AppSchedulesCreateRoute
  '/_app/settings/data-management': typeof AppSettingsDataManagementRoute
  '/_app/students/create': typeof AppStudentsCreateRoute
  '/_app/tools/create': typeof AppToolsCreateRoute
  '/_app/classes/': typeof AppClassesIndexRoute
  '/_app/experiments/': typeof AppExperimentsIndexRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_app/schedules/': typeof AppSchedulesIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/_app/tools/': typeof AppToolsIndexRoute
  '/_app/classes/$id/edit': typeof AppClassesIdEditRoute
  '/_app/experiments/$id/edit': typeof AppExperimentsIdEditRoute
  '/_app/groups/$id/edit': typeof AppGroupsIdEditRoute
  '/_app/schedules/$id/edit': typeof AppSchedulesIdEditRoute
  '/_app/students/$id/edit': typeof AppStudentsIdEditRoute
  '/_app/tools/$id/edit': typeof AppToolsIdEditRoute
  '/_app/classes/$id/': typeof AppClassesIdIndexRoute
  '/_app/experiments/$id/': typeof AppExperimentsIdIndexRoute
  '/_app/groups/$id/': typeof AppGroupsIdIndexRoute
  '/_app/schedules/$id/': typeof AppSchedulesIdIndexRoute
  '/_app/students/$id/': typeof AppStudentsIdIndexRoute
  '/_app/tools/$id/': typeof AppToolsIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/auth/login'
    | '/'
    | '/classes/create'
    | '/experiments/create'
    | '/groups/create'
    | '/schedules/create'
    | '/settings/data-management'
    | '/students/create'
    | '/tools/create'
    | '/classes'
    | '/experiments'
    | '/groups'
    | '/schedules'
    | '/students'
    | '/tools'
    | '/classes/$id/edit'
    | '/experiments/$id/edit'
    | '/groups/$id/edit'
    | '/schedules/$id/edit'
    | '/students/$id/edit'
    | '/tools/$id/edit'
    | '/classes/$id'
    | '/experiments/$id'
    | '/groups/$id'
    | '/schedules/$id'
    | '/students/$id'
    | '/tools/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/auth/login'
    | '/'
    | '/classes/create'
    | '/experiments/create'
    | '/groups/create'
    | '/schedules/create'
    | '/settings/data-management'
    | '/students/create'
    | '/tools/create'
    | '/classes'
    | '/experiments'
    | '/groups'
    | '/schedules'
    | '/students'
    | '/tools'
    | '/classes/$id/edit'
    | '/experiments/$id/edit'
    | '/groups/$id/edit'
    | '/schedules/$id/edit'
    | '/students/$id/edit'
    | '/tools/$id/edit'
    | '/classes/$id'
    | '/experiments/$id'
    | '/groups/$id'
    | '/schedules/$id'
    | '/students/$id'
    | '/tools/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/about'
    | '/auth/login'
    | '/_app/'
    | '/_app/classes/create'
    | '/_app/experiments/create'
    | '/_app/groups/create'
    | '/_app/schedules/create'
    | '/_app/settings/data-management'
    | '/_app/students/create'
    | '/_app/tools/create'
    | '/_app/classes/'
    | '/_app/experiments/'
    | '/_app/groups/'
    | '/_app/schedules/'
    | '/_app/students/'
    | '/_app/tools/'
    | '/_app/classes/$id/edit'
    | '/_app/experiments/$id/edit'
    | '/_app/groups/$id/edit'
    | '/_app/schedules/$id/edit'
    | '/_app/students/$id/edit'
    | '/_app/tools/$id/edit'
    | '/_app/classes/$id/'
    | '/_app/experiments/$id/'
    | '/_app/groups/$id/'
    | '/_app/schedules/$id/'
    | '/_app/students/$id/'
    | '/_app/tools/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/auth/login"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/about",
        "/_app/",
        "/_app/classes/create",
        "/_app/experiments/create",
        "/_app/groups/create",
        "/_app/schedules/create",
        "/_app/settings/data-management",
        "/_app/students/create",
        "/_app/tools/create",
        "/_app/classes/",
        "/_app/experiments/",
        "/_app/groups/",
        "/_app/schedules/",
        "/_app/students/",
        "/_app/tools/",
        "/_app/classes/$id/edit",
        "/_app/experiments/$id/edit",
        "/_app/groups/$id/edit",
        "/_app/schedules/$id/edit",
        "/_app/students/$id/edit",
        "/_app/tools/$id/edit",
        "/_app/classes/$id/",
        "/_app/experiments/$id/",
        "/_app/groups/$id/",
        "/_app/schedules/$id/",
        "/_app/students/$id/",
        "/_app/tools/$id/"
      ]
    },
    "/_app/about": {
      "filePath": "_app/about.tsx",
      "parent": "/_app"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/classes/create": {
      "filePath": "_app/classes/create.tsx",
      "parent": "/_app"
    },
    "/_app/experiments/create": {
      "filePath": "_app/experiments/create.tsx",
      "parent": "/_app"
    },
    "/_app/groups/create": {
      "filePath": "_app/groups/create.tsx",
      "parent": "/_app"
    },
    "/_app/schedules/create": {
      "filePath": "_app/schedules/create.tsx",
      "parent": "/_app"
    },
    "/_app/settings/data-management": {
      "filePath": "_app/settings/data-management.tsx",
      "parent": "/_app"
    },
    "/_app/students/create": {
      "filePath": "_app/students/create.tsx",
      "parent": "/_app"
    },
    "/_app/tools/create": {
      "filePath": "_app/tools/create.tsx",
      "parent": "/_app"
    },
    "/_app/classes/": {
      "filePath": "_app/classes/index.tsx",
      "parent": "/_app"
    },
    "/_app/experiments/": {
      "filePath": "_app/experiments/index.tsx",
      "parent": "/_app"
    },
    "/_app/groups/": {
      "filePath": "_app/groups/index.tsx",
      "parent": "/_app"
    },
    "/_app/schedules/": {
      "filePath": "_app/schedules/index.tsx",
      "parent": "/_app"
    },
    "/_app/students/": {
      "filePath": "_app/students/index.tsx",
      "parent": "/_app"
    },
    "/_app/tools/": {
      "filePath": "_app/tools/index.tsx",
      "parent": "/_app"
    },
    "/_app/classes/$id/edit": {
      "filePath": "_app/classes/$id/edit.tsx",
      "parent": "/_app"
    },
    "/_app/experiments/$id/edit": {
      "filePath": "_app/experiments/$id/edit.tsx",
      "parent": "/_app"
    },
    "/_app/groups/$id/edit": {
      "filePath": "_app/groups/$id/edit.tsx",
      "parent": "/_app"
    },
    "/_app/schedules/$id/edit": {
      "filePath": "_app/schedules/$id/edit.tsx",
      "parent": "/_app"
    },
    "/_app/students/$id/edit": {
      "filePath": "_app/students/$id/edit.tsx",
      "parent": "/_app"
    },
    "/_app/tools/$id/edit": {
      "filePath": "_app/tools/$id/edit.tsx",
      "parent": "/_app"
    },
    "/_app/classes/$id/": {
      "filePath": "_app/classes/$id/index.tsx",
      "parent": "/_app"
    },
    "/_app/experiments/$id/": {
      "filePath": "_app/experiments/$id/index.tsx",
      "parent": "/_app"
    },
    "/_app/groups/$id/": {
      "filePath": "_app/groups/$id/index.tsx",
      "parent": "/_app"
    },
    "/_app/schedules/$id/": {
      "filePath": "_app/schedules/$id/index.tsx",
      "parent": "/_app"
    },
    "/_app/students/$id/": {
      "filePath": "_app/students/$id/index.tsx",
      "parent": "/_app"
    },
    "/_app/tools/$id/": {
      "filePath": "_app/tools/$id/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
